---

- name: Load OS specific vars
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}-{{ ansible_architecture }}.yml"

- name: Load OS Family specific vars
  when: bigfix_client_file_sum is not defined
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_version.split('.')[0] }}-{{ ansible_architecture }}.yml"

- name: Failing due to undetermined OS
  fail:
    msg: OS could not be determined.
  when: bigfix_client_file_sum is not defined

- name: Check for BigFix
  stat:
    path: "{{ bigfix_client_conf_dir }}/.ansible_installed"
  register: bigfix_installed

- include: install.yml
  when: not bigfix_installed.stat.exists or bigfix_update is defined

- name: determine if masthead already exists
  stat:
    path: "{{ bigfix_client_conf_dir }}/actionsite.afxm"
  register: masthead_file

- name: Download masthead from BigFix Server
  get_url:
    url: "http://{{ bigfix_client_server_name }}:{{ bigfix_client_server_port }}/masthead/masthead.afxm"
    dest: "{{ bigfix_client_conf_dir }}/actionsite.afxm"
  when: not masthead_file.stat.exists

- name: Start the service
  service:
    name: "{{ bigfix_client_service_name }}"
    state: restarted
    enabled: true
